In [1]:
import numpy as np
import so101
import math_utils

In [4]:
# Desired end-effector transform: identity rotation, translation [0.1, 0.1, 0]
desired_wge = np.eye(4)
desired_wge[0:3, 3] = np.array([0.1, 0.1, 0.0])

# Call the inverse kinematics solver (returns joint angles in radians)
q_rad = so101.SO101._inverse_kinematics(desired_wge)
q_deg = np.rad2deg(q_rad)

print('Found joint angles (radians):', q_rad)
print('Found joint angles (degrees):', q_deg)

# Verify by forward kinematics using the internal rad-array FK
achieved_wge = so101.SO101._forward_kinematics(q_rad)

error = math_utils.tangent_space_error(achieved_wge, desired_wge)
error_norm = np.linalg.norm(error)
print('Tangent space error (twist):', error)
print('Tangent space error norm:', error_norm)
print('Achieved transform:\n', achieved_wge)
print('desired_wge:\n', desired_wge)


Joint limits (radians): (array([-1.919, -1.74 , -1.69 , -1.65 , -2.74 ]), array([1.919, 1.74 , 1.69 , 1.65 , 2.84 ]))
IK computation time: 1.5766 seconds
IK optimization success: False, message: The maximum number of function evaluations is exceeded.
Found joint angles (radians): [-0.02156913 -0.16743675  1.68975419 -1.49961593  1.57076232]
Found joint angles (degrees): [ -1.23581999  -9.59341902  96.81578352 -85.9216638   89.99805166]
Tangent space error (twist): [[-0.14692228]
 [ 0.09707514]
 [-0.09546   ]
 [ 0.00021082]
 [-0.022701  ]
 [-0.02156782]]
Tangent space error norm: 0.20273850204854893
Achieved transform:
 [[ 9.99509787e-01 -2.15666837e-02  2.26950133e-02  2.49028467e-01]
 [ 2.15618982e-02  9.99767411e-01  4.55574788e-04  4.53438648e-03]
 [-2.26995600e-02  3.39961085e-05  9.99742331e-01  9.37864958e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
desired_wge:
 [[1.  0.  0.  0.1]
 [0.  1.  0.  0.1]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
IK computatio